### ISSUE TITLE
kmers_count running out of memory

### ISSUE THREAD

**Issue by wwood** [sylvainforet/libngs#1]
Hi,

I've been trying to do some kmer counting, and kmers_count seemed to fit the bill - fast and the results I wanted on prototypes. So that was good until I ran into this error, an hour into processing a 3.8G compressed (13G uncompressed) fasta file. Is there something I can do to workaround, perhaps? I'm using the newest github version, 0cfefc7. 

``` sh
$ time pigz -cd E1D.fa.gz |kmers_count --kmer 21 - >E1D.fa.kmers21.csv

(kmers_count:27552): GLib-ERROR **: /build/buildd/glib2.0-2.32.3/./glib/gmem.c:382: overflow allocating 18446744071562067968*24 bytes
Trace/breakpoint trap (core dumped)

real    60m31.239s
user    61m17.754s
sys     1m25.869s
```

That seems like an awful lot of memory to allocate for 21mers, given it is many order of magnitude less than 4^21.

Thanks,
ben

**Comment by wwood** [comment]
sorry I meant it (18446744071562067968*24) is many orders of magnitude _more_ than 4^21.

**Comment by sylvainforet** [comment]
Hi Ben,

Thanks for the report.  This looks like an integer overflow.  I'll check whether I have any 32 bits integer leftover (I am assuming that your system is 64 bits).

Cheers,
SF

**Comment by wwood** [comment]
Right, I'm on a 64 bit system. Thanks.

**Comment by sylvainforet** [comment]
I can't reproduce the error with the same parameters and a 24GB uncompressed fasta file.
Would you be able to make your dataset available to me?
Thanks,
SF

**Comment by wwood** [comment]
Sure mate - do you maybe have an FTP or something?

**Comment by sylvainforet** [comment]
We could use the Aarnet cloudstore:
https://cloudstor.aarnet.edu.au/filesender/
(docs at http://www.aarnet.edu.au/services/cloud-services/cloudstor).
This allows files up to 100GB.
Let me know if that would suit you.
Cheers,
SF

**Comment by sylvainforet** [comment]
We could use the Aarnet cloudstore:
https://cloudstor.aarnet.edu.au/filesender/
(docs at http://www.aarnet.edu.au/services/cloud-services/cloudstor).
This allows files up to 100GB.
Let me know if that would suit you.
Cheers,
SF

**Comment by wwood** [comment]
Sounds perfect, only I'll need your email address. Happy to keep it
off-list - I'm b.woodcroft@uq - I assume you know the rest.

On 31 January 2013 07:59, sylvainforet notifications@github.com wrote:

> We could use the Aarnet cloudstore:
> https://cloudstor.aarnet.edu.au/filesender/
> (docs at http://www.aarnet.edu.au/services/cloud-services/cloudstor).
> This allows files up to 100GB.
> Let me know if that would suit you.
> Cheers,
> SF
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sylvainforet/libngs/issues/1#issuecomment-12914934.

## 

## 

Ben Woodcroft
http://ecogenomic.org/users/ben-woodcroft http://www.ecogenomic.org/

**Comment by sylvainforet** [comment]
OK, this should be fixed in the latest commit.
It was indeed caused by an integer overflow.
Thanks again for the report and let me know how you go with that new version.
Cheers,
SF

**Comment by wwood** [comment]
Seems to work for me now. Cheers.

```
$ time pigz -cd E1D.fa.gz |./libngs_test/bin/kmers_count --kmer 21 - >E1D.fa.kmers21.csv

real    114m25.184s
user    112m29.602s
sys     3m32.065s
```
